// generated by unplugin-svelte-components
// We suggest you to commit this file into source control
declare global {
    const Hello: typeof import("./components/Hello.svelte")["default"]
    const Icon: typeof import("@iconify/svelte")["default"]
}

export {}
